spring:
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://localhost:5434/persondb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

