services:

  api-gateway:
    image: api-gateway
    depends_on:
      - discovery-service
    networks:
      - example-network


  discovery-service:
    image: discovery-service
    networks:
      - example-network
    ports:
      - "8761:8761"

  auth-service:
    image: auth-service
    depends_on:
      - discovery-service
      - postgres-auth
    networks:
      - example-network

  person-service:
    image: person-service
    depends_on:
      - discovery-service
      - postgres-person
    networks:
      - example-network

  request-service:
    image: request-service
    depends_on:
      - discovery-service
      - postgres-request

  postgres-auth:
    image: postgres:latest
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - example-network

  postgres-person:
    image: postgres:latest
    environment:
      POSTGRES_DB: persondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - example-network

  postgres-request:
    image: postgres:latest
    environment:
      POSTGRES_DB: requestdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - example-network

networks:
  example-network:
    driver: bridge